// Cross-language canonicalization conformance test (audit C-11).
//
// Reads each (input.json, expected.bin) pair from the shared fixture
// directory and asserts that `canonicalize` (the npm RFC 8785 library used
// by the verifier) produces byte-for-byte the same output as serde_jcs did
// when the fixture was generated by the Rust counterpart at
// crates/witness-core/tests/canonicalization_conformance.rs.

import * as fs from "node:fs";
import * as path from "node:path";
import * as url from "node:url";
import canonicalizeJson from "canonicalize";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const FIXTURES_DIR = path.resolve(
  __dirname,
  "../../..",
  "tests/fixtures/canonicalization-conformance",
);

interface Case {
  name: string;
  inputPath: string;
  expectedPath: string;
}

function discoverCases(): Case[] {
  if (!fs.existsSync(FIXTURES_DIR)) {
    throw new Error(
      `canonicalization-conformance fixtures missing at ${FIXTURES_DIR}. ` +
        `run \`cargo test -p witness-core --test canonicalization_conformance\` first to generate them.`,
    );
  }
  const entries = fs.readdirSync(FIXTURES_DIR);
  const cases: Case[] = [];
  for (const entry of entries) {
    if (!entry.endsWith(".input.json")) continue;
    const name = entry.slice(0, -".input.json".length);
    cases.push({
      name,
      inputPath: path.join(FIXTURES_DIR, entry),
      expectedPath: path.join(FIXTURES_DIR, `${name}.expected.bin`),
    });
  }
  cases.sort((a, b) => a.name.localeCompare(b.name));
  return cases;
}

function assert(condition: boolean, message: string): void {
  if (!condition) {
    throw new Error(`ASSERTION FAILED: ${message}`);
  }
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

function describeBytes(a: Uint8Array, b: Uint8Array): string {
  const asString = (bytes: Uint8Array): string => {
    try {
      return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    } catch {
      return Array.from(bytes)
        .map((byte) => byte.toString(16).padStart(2, "0"))
        .join("");
    }
  };
  return `\n  expected (${b.length}B): ${asString(b)}\n  actual   (${a.length}B): ${asString(a)}`;
}

function run(): void {
  const cases = discoverCases();
  assert(cases.length > 0, "no conformance cases found in fixture directory");

  for (const c of cases) {
    const inputText = fs.readFileSync(c.inputPath, "utf-8");
    const parsed: unknown = JSON.parse(inputText);
    const text = canonicalizeJson(parsed);
    if (text === undefined) {
      throw new Error(
        `case ${c.name}: canonicalize returned undefined; the JS library refuses values the Rust side accepted.`,
      );
    }
    const actual = new TextEncoder().encode(text);
    const expected = new Uint8Array(fs.readFileSync(c.expectedPath));
    if (!bytesEqual(actual, expected)) {
      throw new Error(
        `case ${c.name}: canonical bytes diverge from serde_jcs output.${describeBytes(actual, expected)}`,
      );
    }
    console.log(`PASS ${c.name}`);
  }
  console.log(`\n=== ALL CANONICALIZATION-CONFORMANCE CASES PASSED (${cases.length}) ===`);
}

run();
