// This file is auto-generated by tauri-specta and checked into the repo so
// that `tsc --noEmit` passes before the first Rust build completes.
// It is overwritten whenever `pnpm tauri dev` or `cargo test export_bindings`
// runs in debug mode.

import { invoke } from "@tauri-apps/api/core";

export interface RecordingStarted {
  readonly outPath: string;
  readonly sampleRateHz: number;
  readonly channels: number;
  readonly maxDurationSeconds: number;
}

export interface RecordingFinished {
  readonly path: string;
  readonly durationMs: number;
  readonly sampleRateHz: number;
  readonly channels: number;
}

export interface PickedImages {
  readonly paths: readonly string[];
  readonly count: number;
}

export interface InferenceSummary {
  readonly transcript: string;
  readonly narrativeSummary: string;
  readonly structuredReportJson: string;
  readonly consistencyVerdict: string;
  readonly consistencyReason: string;
  readonly imageDescriptions: readonly string[];
  readonly totalLatencyMs: number;
  readonly reasoningTracePath: string;
}

export interface SealedBundle {
  readonly bundleId: string;
  readonly path: string;
}

export const commands = {
  async initialize_device(): Promise<string> {
    return await invoke<string>("initialize_device");
  },

  async start_recording_cmd(): Promise<RecordingStarted> {
    return await invoke<RecordingStarted>("start_recording_cmd");
  },

  async stop_recording_cmd(): Promise<RecordingFinished> {
    return await invoke<RecordingFinished>("stop_recording_cmd");
  },

  async pick_images_cmd(): Promise<PickedImages> {
    return await invoke<PickedImages>("pick_images_cmd");
  },

  async run_inference_cmd(): Promise<InferenceSummary> {
    return await invoke<InferenceSummary>("run_inference_cmd");
  },

  async seal_bundle_cmd(): Promise<SealedBundle> {
    return await invoke<SealedBundle>("seal_bundle_cmd");
  },
};

export type { RecordingStarted as RecordingResult, SealedBundle as SealResult };
