// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Ensure a device key exists in the OS keychain. Returns the lowercase
	 *  hex SHA-256 of the raw public key (the key id used inside manifests).
	 */
	initializeDevice: () => typedError<string, AppError>(__TAURI_INVOKE("initialize_device")),
	startRecordingCmd: () => typedError<RecordingStarted, AppError>(__TAURI_INVOKE("start_recording_cmd")),
	stopRecordingCmd: () => typedError<RecordingFinished, AppError>(__TAURI_INVOKE("stop_recording_cmd")),
	pickImagesCmd: () => typedError<PickedImages, AppError>(__TAURI_INVOKE("pick_images_cmd")),
	runInferenceCmd: () => typedError<InferenceSummary, AppError>(__TAURI_INVOKE("run_inference_cmd")),
	sealBundleCmd: () => typedError<SealedBundle, AppError>(__TAURI_INVOKE("seal_bundle_cmd")),
	/**  Reveal a sealed bundle in the host file manager. */
	revealBundleCmd: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_bundle_cmd", { path })),
	/**
	 *  Wipe per-capture working files: the audio recording, the reasoning
	 *  trace, the intermediate bundle (if any), and the staged images.
	 *  Closes audit finding T-6.
	 * 
	 *  Idempotent: missing directories are not an error.
	 */
	discardCaptureCmd: () => typedError<null, AppError>(__TAURI_INVOKE("discard_capture_cmd")),
};

/* Types */
/**
 *  Application-level error. `serde::Serialize` flattens the variant into a
 *  stable string so the frontend can branch on it.
 */
export type AppError = ({ NoAudioDevice: {
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; State?: never; UnsupportedAudioConfig?: never } | ({ UnsupportedAudioConfig: {
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never } | ({ AudioStream: {
	detail: string,
} }) & { AlreadyInProgress?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | "NoActiveRecording" | "RecordingAlreadyActive" | "NoCapturedAudio" | 
/**
 *  File-IO error. `Display` strips absolute paths down to a path relative
 *  to `app_local_data_dir` so the user-facing message cannot leak
 *  `/Users/<name>/Library/Application Support/...`. Absolute paths
 *  remain available to `tracing::error!` via [`Self::log_path`].
 */
({ Io: {
	path: string,
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ ImageRejected: {
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; Core?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ Inference: {
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; Core?: never; ImageRejected?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ Core: {
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ State: {
	detail: string,
} }) & { AlreadyInProgress?: never; AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; UnsupportedAudioConfig?: never } | ({ AlreadyInProgress: {
	operation: string,
} }) & { AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | "SidecarUnauthenticated";

export type InferenceSummary = {
	transcript: string,
	narrativeSummary: string,
	structuredReportJson: string,
	consistencyVerdict: string,
	consistencyReason: string,
	imageDescriptions: string[],
	totalLatencyMs: number,
	reasoningTracePath: string,
};

export type PickedImages = {
	paths: string[],
	count: number,
};

export type RecordingFinished = {
	path: string,
	durationMs: number,
	sampleRateHz: number,
	channels: number,
};

export type RecordingStarted = {
	outPath: string,
	sampleRateHz: number,
	channels: number,
	maxDurationSeconds: number,
};

export type SealedBundle = {
	bundleId: string,
	signerKeyId: string,
	path: string,
	signerAlgorithm: string,
	softwareFallback: boolean,
	signerBackendNote: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

