// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Ensure a device key exists in the OS keychain. Returns the lowercase
	 *  hex SHA-256 of the raw public key (the key id used inside manifests).
	 */
	initializeDevice: () => typedError<string, AppError>(__TAURI_INVOKE("initialize_device")),
	startRecordingCmd: () => typedError<RecordingStarted, AppError>(__TAURI_INVOKE("start_recording_cmd")),
	stopRecordingCmd: () => typedError<RecordingFinished, AppError>(__TAURI_INVOKE("stop_recording_cmd")),
	pickImagesCmd: () => typedError<PickedImages, AppError>(__TAURI_INVOKE("pick_images_cmd")),
	runInferenceCmd: () => typedError<InferenceSummary, AppError>(__TAURI_INVOKE("run_inference_cmd")),
	sealBundleCmd: () => typedError<SealedBundle, AppError>(__TAURI_INVOKE("seal_bundle_cmd")),
};

/* Types */
/**
 *  Application-level error. `serde::Serialize` flattens the variant into a
 *  stable string so the frontend can branch on it.
 */
export type AppError = ({ NoAudioDevice: {
	detail: string,
} }) & { AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; State?: never; UnsupportedAudioConfig?: never } | ({ UnsupportedAudioConfig: {
	detail: string,
} }) & { AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never } | ({ AudioStream: {
	detail: string,
} }) & { Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | "NoActiveRecording" | "RecordingAlreadyActive" | "NoCapturedAudio" | ({ Io: {
	path: string,
	detail: string,
} }) & { AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ ImageRejected: {
	detail: string,
} }) & { AudioStream?: never; Core?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ Inference: {
	detail: string,
} }) & { AudioStream?: never; Core?: never; ImageRejected?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ Core: {
	detail: string,
} }) & { AudioStream?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; State?: never; UnsupportedAudioConfig?: never } | ({ State: {
	detail: string,
} }) & { AudioStream?: never; Core?: never; ImageRejected?: never; Inference?: never; Io?: never; NoAudioDevice?: never; UnsupportedAudioConfig?: never };

export type InferenceSummary = {
	transcript: string,
	narrativeSummary: string,
	structuredReportJson: string,
	consistencyVerdict: string,
	consistencyReason: string,
	imageDescriptions: string[],
	totalLatencyMs: number,
	reasoningTracePath: string,
};

export type PickedImages = {
	paths: string[],
	count: number,
};

export type RecordingFinished = {
	path: string,
	durationMs: number,
	sampleRateHz: number,
	channels: number,
};

export type RecordingStarted = {
	outPath: string,
	sampleRateHz: number,
	channels: number,
	maxDurationSeconds: number,
};

export type SealedBundle = {
	bundleId: string,
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

